### ISSUE TITLE
About the whoami in the a2lib.c

### ISSUE THREAD

**Issue by zhaoxiahust** [openpower-cores/a2-boot#2]
Hi guys,

  I have a question about the whoami function. Does this function return the thread id from the software view or the thread id of the exact hardware thread id. In particular, there are 4 SMT threads in an A2I core, and their id is 0, 1, 2, 3. Does the whoami function return the thread id of these 4 threads?

// sc 0x0001
uint32_t whoami(void) {
   uint32_t thread;
   asm volatile(
       "li   3,0x0001\n"
       "sc\n"
       "mr   %0,3\n"
       : "=r"(thread)               // outputs
       :                            // inputs
       : "r0","r3"                  // clobbers       
       );
   return thread;
}`

**Comment by openpowerwtf** [comment]
It's the thread id as defined in hardware (tir).  

```
# thread id
.align 6
sc_whoami:
      mfspr     r3,tir
      rfi
```
UM chapter 2.3
```
The TIR is a read-only register that can be used to distinguish a thread from other threads on the A2 core.
The TIR returns a value n, where n is referred to as “thread n.”
```
